/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rahul.pawar' at '5/22/19 8:35 PM' with Gradle 3.0
 *
 * @author rahul.pawar, @date 5/22/19 8:35 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
